"""Centroides y nombres canónicos de las provincias argentinas para el mapa."""

# lat, lon aproximados del centroide de cada provincia
PROVINCE_CENTROIDS = {
    'Buenos Aires': (-36.5, -60.0),
    'CABA': (-34.61, -58.38),
    'Catamarca': (-28.5, -65.8),
    'Chaco': (-26.4, -60.4),
    'Chubut': (-43.8, -68.9),
    'Córdoba': (-31.4, -64.2),
    'Corrientes': (-28.0, -57.8),
    'Entre Ríos': (-32.0, -59.2),
    'Formosa': (-24.9, -59.9),
    'Jujuy': (-23.3, -65.7),
    'La Pampa': (-37.0, -64.3),
    'La Rioja': (-29.4, -66.9),
    'Mendoza': (-34.6, -68.3),
    'Misiones': (-26.9, -54.5),
    'Neuquén': (-38.6, -70.1),
    'Río Negro': (-40.7, -66.0),
    'Salta': (-24.8, -65.4),
    'San Juan': (-30.9, -68.9),
    'San Luis': (-33.8, -66.0),
    'Santa Cruz': (-48.8, -69.3),
    'Santa Fe': (-31.6, -60.7),
    'Santiago del Estero': (-27.8, -63.3),
    'Tierra del Fuego': (-54.3, -67.7),
    'Tucumán': (-26.9, -65.2),
}

REGION = {
    'Buenos Aires': 'Centro',
    'CABA': 'Centro',
    'Catamarca': 'Norte',
    'Chaco': 'Norte',
    'Chubut': 'Patagonia',
    'Córdoba': 'Centro',
    'Corrientes': 'Norte',
    'Entre Ríos': 'Centro',
    'Formosa': 'Norte',
    'Jujuy': 'Norte',
    'La Pampa': 'Centro',
    'La Rioja': 'Cuyo',
    'Mendoza': 'Cuyo',
    'Misiones': 'Norte',
    'Neuquén': 'Patagonia',
    'Río Negro': 'Patagonia',
    'Salta': 'Norte',
    'San Juan': 'Cuyo',
    'San Luis': 'Cuyo',
    'Santa Cruz': 'Patagonia',
    'Santa Fe': 'Centro',
    'Santiago del Estero': 'Norte',
    'Tierra del Fuego': 'Patagonia',
    'Tucumán': 'Norte',
}
